title: "The AI Edge"
description: "Cutting through the noise to bring you the most important AI breakthroughs, practical tools, and tech news that actually matters. No PR fluff, just pure insights."
url: "https://jxromejxxng.github.io"
baseurl: "/ai-news-blog" # the subpath of your site, e.g. /blog
theme: minima

# Minima theme settings
minima:
  skin: dark
  social_links:
    twitter: jxromejxxng
    github: jxromejxxng

show_excerpts: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
