title: "Notes on AGI"
description: "Documenting our collision course with superintelligence and what it means for the rest of us. Strictly no PR fluff."
url: "https://jxromejxxng.github.io"
baseurl: "/ai-news-blog" # the subpath of your site, e.g. /blog
theme: minima

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
